Repository DenverCoder1/table2ascii, pull requests merged in 2022-10, with the labels that each got.

#44 refactor: Annotate value type with SupportsStr protocol
  README.md
  requirements.txt
  table2ascii/annotations.py
  table2ascii/table_to_ascii.py
  tests/test_convert.py
Labels: refactor

#45 feat: Add `ascii_rounded` and `ascii_rounded_box` table styles
  docs/source/styles.rst
  table2ascii/preset_style.py
  tests/test_styles.py
Labels: enhancement

#50 feat: Added `plain` table style
  table2ascii/preset_style.py
  tests/test_styles.py
Labels: enhancement

#51 refactor: Support for mypy and add to lint workflow
  .github/workflows/lint.yml
  pyproject.toml
  setup.py
  table2ascii/annotations.py
  table2ascii/preset_style.py
  table2ascii/py.typed
  table2ascii/table_to_ascii.py
Labels: refactor

#52 feat: Add `cell_padding` configurable option
  README.md
  docs/source/usage.rst
  table2ascii/options.py
  table2ascii/table_to_ascii.py
  tests/test_cell_padding.py
Labels: enhancement

#55 docs(readme): Readability improvements and subheading emojis
  README.md
Labels: documentation

#56 ci: Add Pyright linting for Python 3.11
  .github/workflows/lint.yml
  pyproject.toml
Labels: chore

#57 chore: Bump version to 0.5.0
  table2ascii/__init__.py
Labels: chore
